# Control file for continuous integration testing at http://travis-ci.org/

language: c
compiler:
  - clang
  - gcc
os:
- linux
- osx

sudo: false

install: make all
script: make test

# Gitter notifications
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6945dcbee7845a3c8966
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
